### ISSUE TITLE
Windows (VS2019) Release build won't connect

### ISSUE THREAD

**Issue by kebby** [aws/aws-cdi-sdk#17]
I can't seem to open a Tx connection to a remote receiver with the VS2019 release build of the SDK.

This happened to me when trying to run my own transmitter code against the min_rx example but it also occurs with min_tx and min_rx themselves.

Steps to reproduce:
- Get two suitable EC2 instances with EFA
- Install VS2019 on both instances, download the AWS SDK, compile as debug
- Try to run the min_tx and min_rx examples on the two respective machines
- comment out #define METRICS_GATHERING_SERVICE_ENABLED because there seems to be a null check missing somewhere, compile again
- Successfully run the examples
- Try the same in the Release config
-> Examples fail to connect

Command line I used:
./cdi_test_min_tx.exe --local_ip 172.31.xx.yyy --tx AVM --remote_ip 172.31.xx.zzz --dest_port 2000 --rate 60 --num_transactions 100 --payload_size 5184000
(and receiver commandline with the respective address)

What happens in the error case is that the Tx example gets stuck on "[main:440] Waiting to establish connection with remote target..." while the Rx example at least seems to get something but only outputs a "[LibFabricEndpointOpen:266] Using local EFA device GID[....]" once per second.

Another important thing: If you run the Rx and Tx examples on the same machine, it works! The issue only occurs when trying to send data between two instances.

I tried changing a handful of compiler settings (used toolset/runtime, optimization settings, etc) but that didn't change anything.

**Comment by mhhen** [comment]
To clarify, the Debug variant worked correctly between two instances but the Release version did not?

**Comment by kebby** [comment]
Yes. :)

**Comment by trevorheaws** [comment]
Thank you for reaching out, I was wondering if you would be able to send a more complete log that we could review. I have a couple of possible suggestions:

1. I am able to recreate something that matches the symptoms you describe if the Windows firewall is blocking the test application https://github.com/aws/aws-cdi-sdk/blob/mainline/INSTALL_GUIDE_WINDOWS.md#allow-test-applications-in-windows-firewall. If I add aws-cdi-sdk/proj/x64/Debug/*.exe applications to the firewall “Allowed apps” but I do not add aws-cdi-sdk/proj/x64/Release/*.exe applications to that list then the Debug apps work but the Release apps fail exactly as you described.
 
2. Since you mentioned commenting out #define METRICS_GATHERING_SERVICE_ENABLED in src/cdi/configuration.h I think it would be worth also commenting out #define CLOUDWATCH_METRICS_ENABLED in the same file. This assures that the AWS SDP C++ is not having any interactions with the rest of the AWS CDI SDK code. I feel this is unlikely to be the issue but it eliminates some variables.
 
3. Review security group configurations. This doesn’t answer why it would work for Debug but not Release but for connection issues it is worth reviewing https://github.com/aws/aws-cdi-sdk#create-an-efa-enabled-instance to make sure that the correct security rules are in place.

**Comment by kebby** [comment]
Hi,

Seems it was in fact a firewall misconfiguration on the Tx side. My bad :/

But as it seems that the Rx side tries to connect back to Tx somehow and fails (or timeouts), can we get a log warning in that case? It would make situations like this easier to diagnose.

**Comment by mhhen** [comment]
Glad to hear that your issue has been resolved. We will update the documentation and add more details concerning the configuration requirements for both Debug and Release builds.

Concerning your question about connection log warnings, the release version of the cdi_test application does support additional log information. When used with "DEBUG" log level, the "PROBE" and "ENDPOINT_MANAGER" components can be used to generate detailed log messages related to connection states. The cdi_test command line options are shown below:

**--log_component "PROBE ENDPOINT_MANAGER"
--log_level DEBUG**

Will we be adding some additional log messages to the preview branch that are generated at the "INFO" log level. Messages such as:

**Sending connection request.
Received connection request.
Received connection response.
No reply to connection response received.**
