### ISSUE TITLE
Tx reports successful connection status (kCdiConnectionStatusConnected) and payload transmitted, while no Rx created. SOCKET adapter only.

### ISSUE THREAD

**Issue by AlexImagineComm** [aws/aws-cdi-sdk#24]
Please see the full description of my test and output here:
[Tx_RAW_SOCKET_problem.zip](https://github.com/aws/aws-cdi-sdk/files/5751920/Tx_RAW_SOCKET_problem.zip)

The problem is as the following: if I use the following configuration of the **Tx**:
- SOCKET adapter (not reproducible with the EFA)
- RAW type of the payload (did not try the AVM)
- local or remote IP of the Rx. 
- The **Rx NEVER** started on this IP and/or port.
1. The CDI triggers CdiTxConfigData.CdiCoreConnectionCallback with the` cb_data_ptr->status_code == kCdiConnectionStatusConnected`, informing that the connection was accepted.
2. After that the CDI triggers CdiRawTxCallback with `cb_data_ptr->core_cb_data.status_code == kCdiStatusOk`, informing that the payload was transferred successfully, even NO Rx even exists.
3. I think this is the bug and no callback should be even called or should have failure code (like `kCdiConnectionStatusDisconnected`) in the case **no Rx exists**. This is the way EFA works and I expect the SOCKET to work the same way.
4. The issue is important because the SOCKET adapter allows us to debug the the code on local machine, without EC2 involvement. As well we wanted to allow user to run in both modes SOCKET or EFA and expect them to behave exactly the same.

Regards
Alex

**Comment by danengholm** [comment]
Alex,

Thank you for the report. Please understand that the SOCKET adapter type was implemented to provide similar but not equivalent functionality to the EFA. Your query has pointed out a deficiency in our documentation where we should point out the limitations of the SOCKET adapter.
- The SOCKET adapter implementation uses kernel UDP sockets​.
- Throughput is limited particularly in comparison to EFA due to the use of kernel sockets instead of EFA's user space, polled mode network driver.
- UDP does not offer the reliable delivery of messages (datagrams for UDP) that EFA does. The CDI SDK depends on all data messages being delivered by the underlying network transport.
- The out of band connection management used with EFA is not also used with the SOCKET adapter so the transmitting side does not have any way to tell whether the receiving side is present.
- The CDI SDK does not implement out of band connection management if kCdiAdapterTypeSocket is specified in the call to CdiCoreNetworkAdapterInitialize() unlike if kCdiAdapterTypeEfa is specified, therefore the transmitting side has no way to tell whether the receiving side is present.
​
Due to these differences, successful use of the SOCKET adapter requires special consideration.

1. Keep the bandwidth utilization low. This can be done by using small payloads (small raster sizes if using the AVM interface) and/or low frame rates.
2. Ensure that the receive side is started before the transmit side.
3. Use the local interface which should work more reliably than a physical network interface.​
4. Possibly tune the kernel to increase network buffer sizes.

While some of these shortcomings could be overcome, doing so would be a large undertaking which is not a priority given the intended use of the SOCKET interface. It has been usable for testing by AWS Elemental so long as its limitations are honored.​ We will update the SDK documentation with this information.

**Comment by trevorheaws** [comment]
Alex,

AWS CDI SDK release v2.0.2 documented the limitations outlined in our previous post as part of the generated documentation for kCdiAdapterTypeSocket. Please let us know if you have any questions or concerns about the limitations which we previously outlined.
