### ISSUE TITLE
CdiAvmBaselineProfileVersion setting and checking

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#59]
Regarding closes ticket Jpeg-XS receive #58
Changes in  AVM specification will require different version. This means that we need to add version check in RX, to ensure our current code will ignore data from other vendors if they switch to the new version before we do.
Currently there is no limitation on the numbers placed in the version field. If we check for 1.0 and another vendor, who uses the same SDK, sets the version to 3.4 because he wishes to do so, then the version check will fail even though we use the same code.
Questions:
1. What version should we check for?
2. Is it mandatory for all vendors to set version field as 1.0?

**Comment by mhhen** [comment]
Avi,

You are correct. There is no limitation on the numbers placed in the version field. However, they should match the specification being supported. For example "2.00" should be used for Baseline video specification version 2.00. [Example baseline specification](https://cdi.elemental.com/specs/baseline-video-vxx.yy.html).

1. You should be checking for version numbers that are supported by the version of the SDK you are using. Currently, if the version numbers are not recognized by your application, then an out-of-band mechanism must be used to notify the transmitter of the incompatibility. In order to resolve this problem and support additional profiles such as JPEG-XS (#58), we will review the requirement of adding support to the SDK to allow profile version negotiation.
2. Since the SDK currently supports two profile versions, "1.00" and "2.00", vendors should use them. As additional protocols are made available, new version numbers can be used.

We will leave this ticket open and update it with new information as it becomes available.

**Comment by AviManor** [comment]
Thank you Mike for your clarification
As it looks now, only version 1.0 is valid.
We have two options:
1. Make our RX code accept only version 1.0 and reject any other version, assuming higher versions will include different fields, not overlapping version 1.0 fields.
2. Make our current code accept version 1.0 and higher versions, assuming the higher versions will include all fields of version 1.0 in the same order and size, and additional fields are placed above version 1.0 fields.
We need to know which option you plan to choose, so we can build our code correctly.

**Comment by mhhen** [comment]
Avi,

There are currently two profiles available: [1.00](https://github.com/aws/aws-cdi-sdk/blob/3f54945f98ff340947a37cfba3fd84625146eef8/src/cdi/baseline_profiles_1_00.c#L30) and [2.00](https://github.com/aws/aws-cdi-sdk/blob/3f54945f98ff340947a37cfba3fd84625146eef8/src/cdi/baseline_profiles_2_00.c#L30).

We plan on option 2. New fields would be appended to the end of the existing structure for future baseline profiles. Also, additional values may be appended to an individual enumeration, as long as the size of the field does not change.

**Comment by AviManor** [comment]
Thanks Mike
We will build our code according to option 2
Avi
